---
services:
  traefik:
    command:
      - "--providers.docker=true"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.filename=/etc/traefik/traefik_dynamic.yml"
      - "--log.level=INFO"
    volumes:
      - /etc/ssl/certs:/etc/ssl/certs:ro
      - /etc/pki:/etc/pki:ro
      - ${PWD}/traefik/traefik_dynamic-prod.yml:/etc/traefik/traefik_dynamic.yml:ro
    secrets:
      - ssl_key_file

secrets:
  ssl_key_file:
    file: ${HOME}/.ssh/crashweb.key
